# Generated by Django 6.0.8 on 2026-08-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
