# Generated by Django 6.0.8 on 2026-08-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0002_alter_armor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
