# Generated by Django 6.0.8 on 2026-08-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0003_history_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actors/')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
