# Generated by Django 6.0.8 on 2026-08-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0004_actor_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='stark_industries/')),
            ],
        ),
    ]
