# Generated by Django 6.0.8 on 2026-08-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0005_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
