# Generated by Django 6.0.8 on 2026-08-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0007_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
