# Generated by Django 6.0.8 on 2026-08-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0009_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
