# Generated by Django 6.0.8 on 2026-08-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0010_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='films',
            field=models.TextField(blank=True),
        ),
    ]
